

export const mockInventoryItems = [
  {
    _id: '1',
    materialCode: 'CBL-FO-24',
    materialName: 'Fiber Optic Cable 24-Core',
    category: 'telecom',
    location: 'WH-001',
    locationName: 'Main Warehouse',
    totalQuantity: 500,
    availableQuantity: 320,
    allocatedQuantity: 180,
    unit: 'meters',
    conditionBreakdown: {
      excellent: 200,
      good: 200,
      fair: 80,
      poor: 20,
      scrap: 0,
    },
    vendor: 'Corning Inc.',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 500,
      availableQuantity: 320,
      allocatedQuantity: 180,
      inUseQty: 150,
      reservedQty: 30,
      allocationsCount: 3,
    },
  },
  {
    _id: '2',
    materialCode: 'TWR-STL-40',
    materialName: 'Steel Tower Section 40m',
    category: 'tower',
    location: 'WH-001',
    locationName: 'Main Warehouse',
    totalQuantity: 25,
    availableQuantity: 12,
    allocatedQuantity: 13,
    unit: 'piece',
    conditionBreakdown: { excellent: 10, good: 10, fair: 5, poor: 0, scrap: 0 },
    vendor: 'Tower Systems Ltd.',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 25,
      availableQuantity: 12,
      allocatedQuantity: 13,
      inUseQty: 8,
      reservedQty: 5,
      allocationsCount: 2,
    },
  },
  {
    _id: '3',
    materialCode: 'PWR-UPS-5K',
    materialName: 'UPS System 5KVA',
    category: 'power',
    location: 'WH-002',
    locationName: 'Secondary Storage',
    totalQuantity: 15,
    availableQuantity: 8,
    allocatedQuantity: 7,
    unit: 'piece',
    conditionBreakdown: { excellent: 5, good: 6, fair: 3, poor: 1, scrap: 0 },
    vendor: 'APC Corp.',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 15,
      availableQuantity: 8,
      allocatedQuantity: 7,
      inUseQty: 5,
      reservedQty: 2,
      allocationsCount: 4,
    },
  },
  {
    _id: '4',
    materialCode: 'AC-SPLIT-2T',
    materialName: 'Split AC Unit 2 Ton',
    category: 'air_conditioning',
    location: 'WH-001',
    locationName: 'Main Warehouse',
    totalQuantity: 30,
    availableQuantity: 18,
    allocatedQuantity: 12,
    unit: 'piece',
    conditionBreakdown: { excellent: 15, good: 10, fair: 5, poor: 0, scrap: 0 },
    vendor: 'Daikin Industries',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 30,
      availableQuantity: 18,
      allocatedQuantity: 12,
      inUseQty: 10,
      reservedQty: 2,
      allocationsCount: 3,
    },
  },
  {
    _id: '5',
    materialCode: 'SEC-CAM-4K',
    materialName: 'Security Camera 4K IP',
    category: 'security',
    location: 'WH-002',
    locationName: 'Secondary Storage',
    totalQuantity: 100,
    availableQuantity: 45,
    allocatedQuantity: 55,
    unit: 'piece',
    conditionBreakdown: {
      excellent: 40,
      good: 35,
      fair: 20,
      poor: 5,
      scrap: 0,
    },
    vendor: 'Hikvision',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 100,
      availableQuantity: 45,
      allocatedQuantity: 55,
      inUseQty: 40,
      reservedQty: 15,
      allocationsCount: 6,
    },
  },
  {
    _id: '6',
    materialCode: 'CIV-CEM-50',
    materialName: 'Portland Cement 50kg',
    category: 'civil',
    location: 'WH-003',
    locationName: 'Construction Yard',
    totalQuantity: 200,
    availableQuantity: 150,
    allocatedQuantity: 50,
    unit: 'bags',
    conditionBreakdown: {
      excellent: 150,
      good: 50,
      fair: 0,
      poor: 0,
      scrap: 0,
    },
    vendor: 'Dangote Cement',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 200,
      availableQuantity: 150,
      allocatedQuantity: 50,
      inUseQty: 30,
      reservedQty: 20,
      allocationsCount: 2,
    },
  },
  {
    _id: '7',
    materialCode: 'SHL-PRE-3X3',
    materialName: 'Prefab Shelter 3x3m',
    category: 'shelter',
    location: 'WH-001',
    locationName: 'Main Warehouse',
    totalQuantity: 8,
    availableQuantity: 3,
    allocatedQuantity: 5,
    unit: 'piece',
    conditionBreakdown: { excellent: 3, good: 3, fair: 2, poor: 0, scrap: 0 },
    vendor: 'ModularTech',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 8,
      availableQuantity: 3,
      allocatedQuantity: 5,
      inUseQty: 4,
      reservedQty: 1,
      allocationsCount: 2,
    },
  },
  {
    _id: '8',
    materialCode: 'FRN-DSK-EXE',
    materialName: 'Executive Desk',
    category: 'furniture',
    location: 'WH-002',
    locationName: 'Secondary Storage',
    totalQuantity: 20,
    availableQuantity: 14,
    allocatedQuantity: 6,
    unit: 'piece',
    conditionBreakdown: { excellent: 10, good: 8, fair: 2, poor: 0, scrap: 0 },
    vendor: 'Office Solutions',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 20,
      availableQuantity: 14,
      allocatedQuantity: 6,
      inUseQty: 4,
      reservedQty: 2,
      allocationsCount: 1,
    },
  },
  {
    _id: '9',
    materialCode: 'TEL-ANT-5G',
    materialName: '5G Antenna Panel',
    category: 'telecom',
    location: 'WH-001',
    locationName: 'Main Warehouse',
    totalQuantity: 50,
    availableQuantity: 22,
    allocatedQuantity: 28,
    unit: 'piece',
    conditionBreakdown: { excellent: 25, good: 20, fair: 5, poor: 0, scrap: 0 },
    vendor: 'Ericsson',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 50,
      availableQuantity: 22,
      allocatedQuantity: 28,
      inUseQty: 20,
      reservedQty: 8,
      allocationsCount: 5,
    },
  },
  {
    _id: '10',
    materialCode: 'PWR-GEN-50K',
    materialName: 'Diesel Generator 50KVA',
    category: 'power',
    location: 'WH-003',
    locationName: 'Construction Yard',
    totalQuantity: 5,
    availableQuantity: 2,
    allocatedQuantity: 3,
    unit: 'piece',
    conditionBreakdown: { excellent: 2, good: 2, fair: 1, poor: 0, scrap: 0 },
    vendor: 'Caterpillar',
    createdBy: 'user-1',
    summary: {
      totalQuantity: 5,
      availableQuantity: 2,
      allocatedQuantity: 3,
      inUseQty: 2,
      reservedQty: 1,
      allocationsCount: 2,
    },
  },
];

export const mockTotals = {
  totalQuantity: 953,
  availableQuantity: 594,
  allocatedQuantity: 359,
  inUseQty: 273,
  reservedQty: 86,
};

export const categories = [
  { value: 'all', label: 'All Categories' },
  { value: 'civil', label: 'Civil' },
  { value: 'telecom', label: 'Telecom' },
  { value: 'tower', label: 'Tower' },
  { value: 'shelter', label: 'Shelter' },
  { value: 'power', label: 'Power' },
  { value: 'air_conditioning', label: 'Air Conditioning' },
  { value: 'security', label: 'Security' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'others', label: 'Others' },
];

export const locations = [
  { value: 'all', label: 'All Locations' },
  { value: 'WH-001', label: 'Main Warehouse' },
  { value: 'WH-002', label: 'Secondary Storage' },
  { value: 'WH-003', label: 'Construction Yard' },
];

export const statusOptions = [
  { value: 'all', label: 'All Status' },
  { value: 'available', label: 'Available' },
  { value: 'inUse', label: 'In Use' },
  { value: 'allocated', label: 'Allocated' },
  { value: 'zero', label: 'Zero Stock' },
];
